import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { ReduxProviders } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "코드 리뷰 플랫폼",
  description:
    "Generated by create next app\
  yarn berry",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`relative h-screen ${inter.className}`}>
        <ReduxProviders>
          <Header />
          <div className="pt-14 w-full h-full">{children}</div>
        </ReduxProviders>
      </body>
    </html>
  );
}
